version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_KEY: base64:P8Ekc7rAxPEazM8xyAltP0Oc/a0ViV4mi7RIM1TTx1k=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_users
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
